feat(audioctl): merge sink and source commands
Change-Id: Ib3110ff104ad10472d89a70d335e4f03e9591a5e

diff --git a/.local/bin/audioctl b/.local/bin/audioctl
--- a/.local/bin/audioctl
+++ b/.local/bin/audioctl
@@ -2,11 +2,12 @@
 
 set -eu
 
-AUDIOCTL_LIMIT="${AUDIOCTL_LIMIT:-2.0}"
+app="$(basename "$0")"
 
 getvol() {
-	vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
-	[ -n "$vol" ] || return 1
+	[ "$1" ] || return 1
+	vol="$(wpctl get-volume "$1")"
+	[ "$vol" ] || return 1
 	[ "$vol" != "${vol%\[MUTED\]}" ] && {
 		echo "muted"
 		return 0
@@ -14,92 +15,58 @@ getvol() {
 	numfmt --from-unit=100 --format="%.0f" "${vol#Volume: }"
 }
 
-getmic() {
-	vol="$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@)"
-	[ -n "$vol" ] || return 1
-	[ "$vol" != "${vol%\[MUTED\]}" ] && {
-		echo "muted"
-		return 0
-	}
-	numfmt --from-unit=100 --format="%.0f" "${vol#Volume: }"
-}
-
-case "${1:-get}" in
-	get)
-		vol="$(getvol)" || exit $?
-		echo "$vol%"
+case "${1:-output}" in
+	out | output | sink)
+		id="@DEFAULT_AUDIO_SINK@"
+		title="output"
+		limit="2.0"
 		;;
-	toggle)
-		wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
-		;;
-	mute)
-		wpctl set-mute @DEFAULT_AUDIO_SINK@ 1
-		;;
-	unmute)
-		wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
-		;;
-	*+ | *- | *%)
-		wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
-		wpctl set-volume @DEFAULT_AUDIO_SINK@ "$1" --limit "$AUDIOCTL_LIMIT"
-		;;
-	mic)
-		case "${2:-get}" in
-			get)
-				wpctl get-volume @DEFAULT_AUDIO_SOURCE@
-				;;
-			mute)
-				wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 1
-				;;
-			unmute)
-				wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 0
-				;;
-			toggle)
-				wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
-				;;
-			*+ | *- | *%)
-				wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 0
-				wpctl set-volume @DEFAULT_AUDIO_SOURCE@ "$2"
-				;;
-			*)
-				echo "$(basename "$0"): $1: invalid subcommand: $2" >&2
-				exit 1
-				;;
-		esac
-		mic_vol="$(getmic)" || exit $?
-		app="$(basename "$0")"
-		text="$mic_vol%"
-		[ "$mic_vol" = "muted" ] && {
-			mic_vol=0
-			text="muted"
-		}
-		notify-send \
-			-u low \
-			-t 1000 \
-			-a "$app" \
-			-h "int:value:$mic_vol" \
-			-h "string:x-canonical-private-synchronous:$app-volume" \
-			"microphone" \
-			"$text"
-		exit 0
+	in | input | source)
+		id="@DEFAULT_AUDIO_SOURCE@"
+		title="input"
+		limit="1.0"
 		;;
 	*)
-		echo "$(basename "$0"): invalid command: $1" >&2
+		echo "$app: invalid command: $1" >&2
 		exit 1
 		;;
 esac
 
-vol="$(getvol)" || exit $?
-app="$(basename "$0")"
+case "${2:-get}" in
+	get)
+		vol="$(getvol "$id")"
+		echo "$vol%"
+		;;
+	toggle)
+		wpctl set-mute "$id" toggle
+		;;
+	mute)
+		wpctl set-mute "$id" 1
+		;;
+	unmute)
+		wpctl set-mute "$id" 0
+		;;
+	*+ | *- | *%)
+		wpctl set-mute "$id" 0
+		wpctl set-volume "$id" "$2" --limit "${AUDIOCTL_LIMIT:-$limit}"
+		;;
+	*)
+		echo "$app: invalid subcommand: $2" >&2
+		;;
+esac
+
+vol="$(getvol "$id")" || exit $?
 text="$vol%"
 [ "$vol" = "muted" ] && {
 	vol=0
 	text="muted"
 }
+
 notify-send \
 	-u low \
 	-t 1000 \
 	-a "$app" \
 	-h "int:value:$vol" \
 	-h "string:x-canonical-private-synchronous:$app-volume" \
-	"volume" \
+	"$title" \
 	"$text"
