improve volumectl script
Change-Id: Id5142c4886be0147fd5fe7742790325f42a3a4aa

diff --git a/.local/bin/volumectl b/.local/bin/volumectl
--- a/.local/bin/volumectl
+++ b/.local/bin/volumectl
@@ -2,25 +2,31 @@
 
 set -eu
 
+VOLUMECTL_LIMIT="${VOLUMECTL_LIMIT:-1.3}"
+
 getvol() {
 	vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
 	[ -n "$vol" ] || return 1
-	[ "$vol" != "${vol%\[MUTED\]}" ] && echo "muted" && return 0
-	vol="${vol#Volume: }"
-	IFS="."
-	# shellcheck disable=2086
-	set -- ${vol#0}
-	printf "%s" "$@"
+	[ "$vol" != "${vol%\[MUTED\]}" ] && {
+		echo "muted"
+		return 0
+	}
+	numfmt --from-unit=100 --format="%.0f" "${vol#Volume: }"
 }
 
-case "$1" in
+case "${1:-get}" in
 	set) wpctl set-volume @DEFAULT_AUDIO_SINK@ "${2:-60}%" ;;
-	get) getvol && echo "%"; exit $? ;;
+	get)
+		vol="$(getvol)" || exit $?
+		echo "$vol%"
+		;;
+	toggle)
+		wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
+		;;
 	*+ | *- | *%)
 		wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
-		wpctl set-volume @DEFAULT_AUDIO_SINK@ "$1"
+		wpctl set-volume @DEFAULT_AUDIO_SINK@ "$1" --limit "$VOLUMECTL_LIMIT"
 		;;
-	toggle) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
     togglemic)
         wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
 
@@ -43,15 +49,19 @@ case "$1" in
 		fi
 
 		exit 0
-    ;;
-	*) exit 1 ;;
+		;;
+	*)
+		echo "$(basename): invalid command: $1" >&2
+		exit 1
+		;;
 esac
 
-vol="$(getvol)" || exit 1
+vol="$(getvol)" || exit $?
+text="$vol%"
 [ "$vol" = "muted" ] && {
 	vol=0
 	text="muted"
-} || text="$vol%"
+}
 notify-send \
 	-u low \
 	-t 1000 \
